package com.pivotal.q1.model;

// Generated Oct 13, 2014 2:28:43 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Album generated by hbm2java
 */
@Entity
@Table(name = "album", catalog = "rmcdb", uniqueConstraints = @UniqueConstraint(columnNames = "title"))
public class Album implements java.io.Serializable {

	private Integer id;
	private String title;
	private String artist;
	private Set<Song> songs = new HashSet<Song>(0);

	public Album() {
	}

	public Album(String title, String artist) {
		this.title = title;
		this.artist = artist;
	}

	public Album(String title, String artist, Set<Song> songs) {
		this.title = title;
		this.artist = artist;
		this.songs = songs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "title", unique = true, nullable = false, length = 30)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "artist", nullable = false, length = 30)
	public String getArtist() {
		return this.artist;
	}

	public void setArtist(String artist) {
		this.artist = artist;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "album_song", catalog = "rmcdb", joinColumns = { @JoinColumn(name = "albumId", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "songId", nullable = false, updatable = false) })
	public Set<Song> getSongs() {
		return this.songs;
	}

	public void setSongs(Set<Song> songs) {
		this.songs = songs;
	}

}
