package com.pivotal.q1.model;

// Generated Oct 11, 2014 1:22:57 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cat generated by hbm2java
 */
@Entity
@Table(name = "cat", catalog = "rmcdb")
public class Cat implements java.io.Serializable {

	private Long id;
	private Cat mother;
	private String name;
	private Date birthDate;
	private Set<Cat> kittens = new HashSet<Cat>(0);

	public Cat() {
	}

	public Cat(String name, Date birthDate) {
		this.name = name;
		this.birthDate = birthDate;
	}

	public Cat(Cat mother, String name, Date birthDate, Set<Cat> kittens) {
		this.mother = mother;
		this.name = name;
		this.birthDate = birthDate;
		this.kittens = kittens;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MOTHER_ID")
	public Cat getMother() {
		return this.mother;
	}

	public void setMother(Cat mother) {
		this.mother = mother;
	}

	@Column(name = "NAME", nullable = false, length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "BIRTH_DATE", nullable = false, length = 10)
	public Date getBirthDate() {
		return this.birthDate;
	}

	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mother")
	public Set<Cat> getKittens() {
		return this.kittens;
	}

	public void setKittens(Set<Cat> kittens) {
		this.kittens = kittens;
	}

}
