USE rmcdb;

SELECT S.SPRTELE_PIDM, S.SPRTELE_ATYP_CODE, S.SPRTELE_PHONE_NUMBER, S.SPRTELE_STATUS_IND
FROM SPRTELE S
WHERE SPRTELE_STATUS_IND IS NULL 
	AND SPRTELE_ATYP_CODE = 'PR' 
	AND	S.SPRTELE_ACTIVITY_DATE = (
	SELECT MAX(SPRTELE_ACTIVITY_DATE)
	FROM SPRTELE
	WHERE  SPRTELE_PIDM = S.SPRTELE_PIDM AND SPRTELE_STATUS_IND IS NULL );
