USE rmcdb;

DELETE FROM PRODUCT;
DELETE FROM COMPANY;

INSERT INTO COMPANY (NAME,PHONE) VALUES ('IBM','845-489-6914');
INSERT INTO COMPANY (NAME,PHONE) VALUES ('Verizon','914-489-8666');

INSERT INTO PRODUCT (NAME,MANUFACTURER) VALUES ('Lenova',1);
INSERT INTO PRODUCT (NAME,MANUFACTURER) VALUES ('Thinkpad',1);
INSERT INTO PRODUCT (NAME,MANUFACTURER) VALUES ('FileNet',1);
INSERT INTO PRODUCT (NAME,MANUFACTURER) VALUES ('BigBlue',1);
INSERT INTO PRODUCT (NAME,MANUFACTURER) VALUES ('TypeWriter',1);
INSERT INTO PRODUCT (NAME,MANUFACTURER) VALUES ('Cloud Machine',1);
INSERT INTO PRODUCT (NAME,MANUFACTURER) VALUES ('Pure Flex',1);
INSERT INTO PRODUCT (NAME,MANUFACTURER) VALUES ('Z Seriers',1);
INSERT INTO PRODUCT (NAME,MANUFACTURER) VALUES ('Websher',1);
INSERT INTO PRODUCT (NAME,MANUFACTURER) VALUES ('Rational',1);
INSERT INTO PRODUCT (NAME,MANUFACTURER) VALUES ('Lotus Notes',1);
INSERT INTO PRODUCT (NAME,MANUFACTURER) VALUES ('Wireless',2);
INSERT INTO PRODUCT (NAME,MANUFACTURER) VALUES ('Fios',2);
INSERT INTO PRODUCT (NAME,MANUFACTURER) VALUES ('Telephone',2);

COMMIT;