USE rmcdb;

DROP TABLE IF EXISTS PRODUCT;

CREATE TABLE `PRODUCT` (
  `id`	 		bigint(20) 	NOT NULL AUTO_INCREMENT,
  `name`	 	varchar(30) NOT NULL,
  `manufacturer` 	bigint(20) 	NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_PRODUCT_MANUFACTURER` FOREIGN KEY `FK_PRODUCT_MANUFACTURER` (`manufacturer`) REFERENCES `COMPANY` (`id`)  ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

COMMIT;